### ISSUE TITLE
null pointer exception with <feature>FAILED_XOBJECT</feature>

### ISSUE THREAD

**Issue by ilcapitanomark** [veraPDF/veraPDF-apps#142]
Hi,
I have used all features but "FAILED_XOBJECT" is giving a null pointer exception:
Exception in thread "main" java.lang.NullPointerException
	at java.util.EnumSet.typeCheck(EnumSet.java:396)
	at java.util.RegularEnumSet.add(RegularEnumSet.java:161)
	at java.util.RegularEnumSet.add(RegularEnumSet.java:36)
	at com.sun.xml.internal.bind.v2.runtime.reflect.Lister$CollectionLister.addToPack(Lister.java:289)
	at com.sun.xml.internal.bind.v2.runtime.reflect.Lister$CollectionLister.addToPack(Lister.java:253)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Scope.add(Scope.java:106)
	at com.sun.xml.internal.bind.v2.runtime.property.ArrayERProperty$ReceiverImpl.receive(ArrayERProperty.java:198)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.endElement(UnmarshallingContext.java:597)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:165)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
	at org.verapdf.core.XmlSerialiser.typeFromXml(XmlSerialiser.java:135)
	at org.verapdf.core.XmlSerialiser.typeFromXml(XmlSerialiser.java:118)
	at org.verapdf.features.FeatureFactory.configFromXml(FeatureFactory.java:63)
	at org.verapdf.apps.ConfigManagerImpl.getFeaturesConfig(ConfigManagerImpl.java:91)
	at org.verapdf.cli.VeraPdfCliProcessor.<init>(VeraPdfCliProcessor.java:83)
	at org.verapdf.cli.VeraPdfCliProcessor.createProcessorFromArgs(VeraPdfCliProcessor.java:139)
	at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:95)

**Comment by shem-sergey** [comment]
Hello! Thank you for your note.
Feature type FAILED_XOBJECT is obsolete and is not used now. If you launch verapdf-gui and open features config panel you won't find it there.
However it was not removed from documentation and that must have confused you.
We are working on documentation fixes now.

**Comment by carlwilson** [comment]
Documentation fix is now merged so am closing this now.
